# Generated by Django 2.2.14 on 2020-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='names')),
                ('lastname', models.TextField(verbose_name='lastnames')),
                ('email', models.EmailField(max_length=254, verbose_name='emails')),
                ('phone', models.IntegerField(max_length=10, verbose_name='phone')),
                ('plaque', models.TextField(verbose_name='plaque')),
                ('vehicule', models.TextField(verbose_name='vehicule')),
            ],
            options={
                'db_table': 'User',
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
                'ordering': ['id'],
            },
        ),
    ]
